# Configuration of home-row-fu(1)
# Default path of this file is /etc/home-row-fu.toml

# Burst Typing time frame (in millisecond).
#
# This feature allows you to bypass most of the home-row-fu magic and just enter
# the text, if you can (touch) type fast enough.  If the time frame between two
# consecutive key presses is less then this value, keys are treated literally.
# Also, keep in mind that bigger values will force you to wait longer for a key
# to "become" a modifier.
#
# To disable this feature: set to 0.
#
# Default: 200
burst_typing_msec = 200

# Maximum time (in milliseconds) when a key release still inserts a letter.
#
# For example, when you hold down the key F (acts as Left Ctrl by default) key
# for more than 0.7 seconds, then just release it without pressing any follow-up
# keys - only Left Ctrl key press and key release events get sent to the system.
# This mimics the behavior of when you hold and release the real Ctrl key.
#
# To disable this feature: set to 999999.
#
# Default: 700
can_insert_letter_msec = 700

# Add [[mapping]] block for every key you want this plugin to handle.
#
# physical_key and modifier_key value may be either an integer key code
# constant, or its textual name as found in the <input-event-codes.h> header
# file. Usually it is located at /usr/include/linux/input-event-codes.h
#
# immediately_send_modifier parameter controls whether to simulate the
# modifier press immediately after the physical key press (e.g. to be able to
# use Ctrl + Mouse Scroll etc. in browsers). Note that setting this to true for
# Alt will mess with GUI apps, because they tend to immediately activate their
# main menu once Alt is pressed.
#
# Default: false
#
# Hint: META is a Windows-key on most keyboards.

[[mapping]]
physical_key = "KEY_A"
modifier_key = "KEY_LEFTSHIFT"
[[mapping]]
physical_key = "KEY_SEMICOLON"
modifier_key = "KEY_LEFTSHIFT"

[[mapping]]
physical_key = "KEY_S"
modifier_key = "KEY_LEFTALT"
[[mapping]]
physical_key = "KEY_L"
modifier_key = "KEY_RIGHTALT"

[[mapping]]
physical_key = "KEY_D"
modifier_key = "KEY_LEFTMETA"
[[mapping]]
physical_key = "KEY_K"
modifier_key = "KEY_RIGHTMETA"

[[mapping]]
physical_key = "KEY_F"
modifier_key = "KEY_LEFTCTRL"
immediately_send_modifier = true
[[mapping]]
physical_key = "KEY_J"
modifier_key = "KEY_RIGHTCTRL"
immediately_send_modifier = true
