
// Modify these to change key<->modifier correspondence to your
// taste. Available key constants are listed in <input-event-codes.h>
// META is a Windows-key on most keyboards.

DEFINE_MAPPING(KEY_A, KEY_LEFTALT)
DEFINE_MAPPING(KEY_SEMICOLON, KEY_RIGHTALT)

DEFINE_MAPPING(KEY_S, KEY_LEFTSHIFT)
DEFINE_MAPPING(KEY_L, KEY_RIGHTSHIFT)

DEFINE_MAPPING(KEY_D, KEY_LEFTMETA)
DEFINE_MAPPING(KEY_K, KEY_RIGHTMETA)

DEFINE_MAPPING(KEY_F, KEY_LEFTCTRL)
DEFINE_MAPPING(KEY_J, KEY_RIGHTCTRL)
